---
# handlers file for /home/ansible/ansibleproject/roles/apache
- name: start and enable apache 
  service: 
    name=httpd state=restarted enabled=yes
- name: setup firewalld
  firewalld:
    service: http
    permanent: true
    state: enabled
- name: reload firewalld
  service: 
    name: firewalld 
    state: restarted