---
- hosts: all
  become: yes
  become_user: root
  
    tasks:
  
#    - name: Add a new user named ansible
#      user:
#          name=ansible
#          password={{ ansible_password }}
  
  - name: Add ansible user to the sudoers
      copy:
          dest: "/etc/sudoers.d/ansible"
          content: "ansible  ALL=(ALL)  NOPASSWD: ALL"
  
    - name: Deploy SSH Key
      authorized_key: user=ansible
                      key="{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"
                      state=present
  
    - name: Disable Password Authentication
      lineinfile:
            dest=/etc/ssh/sshd_config
            regexp='^PasswordAuthentication'
            line="PasswordAuthentication no"
            state=present
            backup=yes
      notify:
        - restart ssh
  
    - name: Disable Root Login
      lineinfile:
            dest=/etc/ssh/sshd_config
            regexp='^PermitRootLogin'
            line="PermitRootLogin no"
            state=present
            backup=yes
      notify:
        - restart ssh
  
    handlers:
    - name: restart ssh
      service:
        name=sshd
        state=restarted
    
