---

- name: "Ensure that percona is running and enabled"
  service:
    name: "mysql"
    state: "started"
    enabled: "yes"
  register: mysql_service

- name: "Restart percona"
  service: "name=mysql state=restarted"